name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a 
requirements.txt file

    - name: Run tests
      run: |
        python -m unittest discover  # Adjust if you are using a 
different test framewname: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a 
requirements.txt file

    - name: Run tests
      run: |
        python -m unittest discover  # Adjust if you are using a 
different test framework
# 
.github/workflows/python-app.yml
name: Python application

on: [push]  # This triggers the workflow when you push changes

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the code will run

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out your code from GitHub

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Specifies the Python version to use

    - name: Run Python script
      run: |
        python app.py  # This runs the app.py file in your repository
